### PR TITLE
#37 Fix PatternsCS deprecation issue

### PR DESCRIPTION
**Pull request by SimonScholz**
## Purpose

Fix the PatternsCS deprecation issue. See #37 

## References

References #37

### CODE REVIEW

**Comment by raboof** [comment]
Thanks for the PR! The travis issue does not seem to have anything to do with your PR, I'll have a look!

**Comment by SimonScholz** [comment]
@raboof I am not really into sbt, but with Gradle and Maven it works and I am able to get, create and delete users.

I could also change the project/travis config to build everything with gradle rather than using sbt, which I guess is more scala related and I think the majority of java devs like me are not aware of it.

Btw do you also have an example on how to use a persistent actor, which is able to store the requests or users in a DB?
If not, are PRs for this welcome or should I host this in my own repo?

**Comment by raboof** [comment]
I fixed the sbt issue in #39 . 

We have an Akka Persistence sample at https://developer.lightbend.com/start/?group=akka, does that look like what you're looking for?

**Review by raboof — APPROVED** [review]
Thanks for your contribution!

**Comment by TimMoore** [comment]
A solution that would be more idiomatic for Java would be to convert `timeout` to a `java.time.Duration` and use the version of `ask` that takes that type and returns a `CompletionStage`: https://doc.akka.io/japi/akka/current/akka/pattern/Patterns.html#ask(akka.actor.ActorRef,java.lang.Object,java.time.Duration)

**Comment by SimonScholz** [comment]
Thank you, @TimMoore I'll create another PR, which omits the step of creating an scala.concurrent.Future<Object> instance.

**Comment by TimMoore** [comment]
Thanks so much, @SimonScholz!

**Pull request merged**
