### PR TITLE
#37 Make only use of Java API in UserRoutes class

### PR DESCRIPTION
**Pull request by SimonScholz**
## Purpose
Include the proposal of @TimMoore 

## References

References https://github.com/akka/akka-http-quickstart-java.g8/pull/38

## Changes

Only make use of Java API in UserRoutes class

### CODE REVIEW

**Review by TimMoore — COMMENTED** [review]
Thanks!

It looks like this change added some accidental extra indentation. (Tabs instead of spaces?)

**Comment by SimonScholz** [comment]
> Thanks!
> 
> It looks like this change added some accidental extra indentation. (Tabs instead of spaces?)

Yes you're right. Sorry about that. I'll fix it ;-)

**Comment by SimonScholz** [comment]
It was just tabs vs spaces

**Review by TimMoore — APPROVED** [review]

**Review by raboof — APPROVED** [review]
Great! Sorry not to catch this the first time around :D

**Pull request merged**
